node {
    git url: 'https://github.com/MuYoul/ants_ansible.git', branch: 'master'
	
    def msg = """
        ******************
	* tage test
	******************
        """

    stage('[INFO] PREVIEW INFORMATION') {
        echo "배포 정보입니다."
        print msg
        sleep(time: 5, unit: "SECONDS")
    }

    dir ("${env.WORKSPACE}") {
        sh 'pwd'
    }
	
    stage('[INFO] SENCOND STAGE - PREPROCESSING') {
        echo "전역 변수 처리"
        print msg
        sleep(time: 5, unit: "SECONDS")
    }
	
    stage('[INFO] THRID STAGE - MAIN PROCESSING') {
        echo "메인 엔진 설치 및 설정"
        print msg
        sleep(time: 5, unit: "SECONDS")
    }
	
    stage('[INFO] FORUTH STAGE - POST PROCESSING') {
        echo "각종 설정 및 실행"
        print msg
        sleep(time: 5, unit: "SECONDS")
    }
}
